replacement_dict = {
    'Albany': 'Albany (NY)',
    'Bowling Green': 'Bowling Green State',
    'BYU': 'Brigham Young',
    'Central Connecticut': 'Central Connecticut State',
    'UCF': 'Central Florida',
    'Charleston': 'College of Charleston',
    'Detroit': 'Detroit Mercy',
    'FAU': 'Florida Atlantic',
    'Fairleigh Dickinson': 'FDU',
    'FGCU': 'Florida Gulf Coast',
    'FIU': 'Florida International',
    'Grambling State': 'Grambling',
    'UIC': 'Illinois-Chicago',
    'UMKC': 'Kansas City',
    'Long Island': 'Long Island University',
    'LSU': 'Louisiana State',
    'ULM': 'Louisiana-Monroe',
    'Loyola-Chicago': 'Loyola (IL)',
    'Loyola-Maryland': 'Loyola (MD)',
    'UMBC': 'Maryland-Baltimore County',
    'UMass': 'Massachusetts',
    'UMass-Lowell': 'Massachusetts-Lowell',
    'McNeese': 'McNeese State',
    'Ole Miss': 'Mississippi',
    "Mount Saint Mary's": "Mount St. Mary's",
    'North Carolina State': 'NC State',
    'UNLV': 'Nevada-Las Vegas',
    'Nicholls': 'Nicholls State',
    'Penn': 'Pennsylvania',
    'Prairie View A&M': 'Prairie View',
    'Presbyterian College': 'Presbyterian',
    'Queens': 'Queens (NC)',
    "Saint Mary's College": "Saint Mary's (CA)",
    'Sam Houston State': 'Sam Houston',
    'Seattle University': 'Seattle',
    'Southeast Missouri': 'Southeast Missouri State',
    'USC': 'Southern California',
    'SIUE': 'SIU Edwardsville',
    'SMU': 'Southern Methodist',
    'Southern Miss': 'Southern Mississippi',
    'Saint Bonaventure': 'St. Bonaventure',
    "Saint John's": "St. John's (NY)",
    'Saint Thomas': 'St. Thomas',
    'UTRGV': 'Texas-Rio Grande Valley',
    'UNCG': 'UNC Greensboro',
    'UCF': 'UCF',
    'UNCW': 'UNC Wilmington',
    'UTA': 'UT Arlington',
    'VCU': 'Virginia Commonwealth'
}